"""add comment idempotency key

Revision ID: b532e8b700c1
Revises: 783f54e63a0b
Create Date: 2026-10-09 18:36:24.929665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b532e8b700c1'
down_revision: Union[str, Sequence[str], None] = '783f54e63a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('idempotency_key', sa.Uuid(), nullable=True))
    op.create_unique_constraint('uq_comments_author_idempotency_key', 'comments', ['author_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_comments_author_idempotency_key', 'comments', type_='unique')
    op.drop_column('comments', 'idempotency_key')
    # ### end Alembic commands ###
